# Site settings
title:       The Gweek Archives
author:      the Grafik Weekers
description: "A collaborative manual to learn the basic of Photoshop and Illustrator"
baseurl:     "/captains-log" 
url:         "https://mashlo.github.io" 

# Social Links
email:            grafikweek@weeklify.com
twitter_username: grafikweek
github_username:  weeklify

# Build settings
markdown: kramdown
permalink: pretty
